Repository miyuchina/mistletoe, pull requests merged in 2023-12, with the labels that each got.

#188 Add line numbers on all block tokens during parsing (#144)
  dev-guide.md
  mistletoe/block_token.py
  mistletoe/block_tokenizer.py
  mistletoe/markdown_renderer.py
  test/samples/line_numbers.md
  test/test_ast_renderer.py
  test/test_block_token.py
  test/test_line_numbers.py
  test/test_repr.py
Labels: feature

#202 feat(markdown-renderer): option to normalize spacing after the list marker
  mistletoe/markdown_renderer.py
  test/test_markdown_renderer.py
Labels: enhancement

#203 feat: allow just 1 dash in Table delimiter cells (#131)
  mistletoe/block_token.py
  test/test_block_token.py
Labels: enhancement

#204 feat(html-renderer): option to skip HTML tokens parsing (#74)
  mistletoe/html_renderer.py
  test/test_html_renderer.py
Labels: feature

#195 fix inline mathjax handling
  mistletoe/contrib/mathjax.py
  test/test_contrib/test_mathjax.py
Labels: bug
